export const Color = {
    BLACK: "black",
    WHITE: "white",
    SEMI_WHITE: "#efefef",
    SECONDARY_BACKGROUND_0: "#009688",
    SECONDARY_BACKGROUND_LIGHTER_0: "#03c0ad",
    SECONDARY_BACKGROUND_DARKER_0: "#03c0ad",
    SECONDARY_BACKGROUND_1: "#FEEFBC",
    SECONDARY_BACKGROUND_LIGHTER_1: "#fbf2d2",
    SECONDARY_BACKGROUND_DARKER_1: "#bfb181",
}